# MATH 210 Introduction to Mathematical Computing

**April 10, 2024**

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

## Power Method

In [9]:
A = np.array([[1.,1.,0.,0.],[1.,1.,1.,0.],[0.,1.,1.,1.],[0.,0.,1.,1.]])
A

array([[1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [0., 1., 1., 1.],
       [0., 0., 1., 1.]])

In [23]:
x0 = np.array([[1.],[1.],[1.],[1.]])
x0

array([[1.],
       [1.],
       [1.],
       [1.]])

In [24]:
A@A@A@A@A@x0

array([[ 89.],
       [144.],
       [144.],
       [ 89.]])

In [25]:
evals,evecs = la.eig(A)
evals

array([-0.61803399+0.j,  0.38196601+0.j,  2.61803399+0.j,  1.61803399+0.j])

In [26]:
89/34

2.6176470588235294

In [27]:
N = 10
xk = np.array([[1.],[1.],[1.],[1.]])
for k in range(N):
    xk = A@xk
    xk = xk/np.abs(np.max(xk))
xk

array([[0.61803399],
       [1.        ],
       [1.        ],
       [0.61803399]])

In [28]:
89/144

0.6180555555555556