# MATH 210 Introduction to Mathematical Computing

**April 5, 2024**

In [74]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

## Eigenvalues and Eigenvectors

The function `scipy.linalg.eig` returns a tuple where the first value is an array of eigenvalues and the second value in the tuple is the matrix of eigenvectors.

In [77]:
A = np.array([[1.,2.],[2.,1.]])
A

array([[1., 2.],
       [2., 1.]])

In [78]:
result = la.eig(A)
result

(array([ 3.+0.j, -1.+0.j]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [79]:
evals = result[0]
evecs = result[1]

In [80]:
evals

array([ 3.+0.j, -1.+0.j])

In [81]:
evecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

We can unpack the eigenvalues and eigenvectors directly.

In [82]:
evals,evecs = la.eig(A)

In [83]:
evals

array([ 3.+0.j, -1.+0.j])

In [84]:
evecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

The function `la.eig` always returns eigenvalues as complex numbers. We interpret eigenvalues as real if the imaginary part is 0 or very small like `1e-15`.

In [85]:
evals = evals.real
evals

array([ 3., -1.])

Any (nonzero) multiple of an eigenvector is also an eigenvector. The fucntion `la.eig` returns the eigenvectors as a matrix where column `i` corresponds to eigenvalue at index `i` and each column is a unit vector.

In [86]:
A = np.array([[2.,-1.,-1.],[-1.,2.,-1.],[-1.,-1.,2.]])
A

array([[ 2., -1., -1.],
       [-1.,  2., -1.],
       [-1., -1.,  2.]])

In [87]:
evals,evecs = la.eig(A)

In [89]:
evals

array([ 3.00000000e+00+0.j, -4.23796137e-16+0.j,  3.00000000e+00+0.j])

In [90]:
evals.real.round(15)

array([ 3., -0.,  3.])

In [91]:
evecs

array([[ 0.81649658, -0.57735027,  0.25359481],
       [-0.40824829, -0.57735027, -0.79893374],
       [-0.40824829, -0.57735027,  0.54533893]])

In [92]:
1/3**0.5

0.5773502691896258

In [93]:
-1/6**0.5

-0.4082482904638631