# MATH 210 Introduction to Mathematical Computing

**April 8, 2024**

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

## Diagonalization

A matrix $A$ is diagonalizable if there exists an invertible matrix $P$ and diagonal matrix $D$ such that

$$
A = PDP^{-1}
$$

If $A$ is diagonalizable then the columns of $P$ are eigenvectors and the entries of $D$ are eigenvectors.

Not every matrix ia diagonalizable. Basically, a matrix is diagonalizable if and only if it has $n$ linearly independent eigenvectors. Therefore a matrix with $n$ distinct eigenvalues is diagonlizable.

It turns out that all symmetrix matrices are diaglizable also. We won't prove this.

In [2]:
A = np.array([[1.,2.],[2.,1.]])
evals,evecs = la.eig(A)
evals

array([ 3.+0.j, -1.+0.j])

In [3]:
evecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [4]:
Ak = 1/3*A
N = 10
for k in range(N):
    Ak = 1/3*A@Ak
print(Ak)

[[0.49999718 0.50000282]
 [0.50000282 0.49999718]]


In [6]:
A = np.array([[2.,5.],[5.,-1]])
A

array([[ 2.,  5.],
       [ 5., -1.]])

In [7]:
x0 = np.array([1.,1.])
xk = x0
N = 100
for k in range(N):
    xk = A@xk
    xk = xk/np.max(np.abs(xk))
print(xk)

[1.         0.74403065]


In [8]:
xk@A@xk/(xk@xk)

5.720153254455275

In [9]:
evals,evecs = la.eig(A)
evals

array([ 5.72015325+0.j, -4.72015325+0.j])